Fix the NEON build after "Convert CamelCase names to underscore_names."
    This patch fixes the following build error caused
    by commit a98b71eff4041df58c9dcc2b1e25cefa38f364ff
    (Convert CamelCase names to underscore_names.):

    <--   snip  -->

    ...
    pixman-arm-neon.c: In function 'neon_composite_over_n_8_0565':
    pixman-arm-neon.c:1784: error: 'x_dst' undeclared (first use in this function)
    pixman-arm-neon.c:1784: error: (Each undeclared identifier is reported only once
    pixman-arm-neon.c:1784: error: for each function it appears in.)
    pixman-arm-neon.c:1785: error: 'p_dst' undeclared (first use in this function)
    pixman-arm-neon.c: In function 'neon_composite_over_n_0565':
    pixman-arm-neon.c:1937: error: 'x_dst' undeclared (first use in this function)
    pixman-arm-neon.c:1938: error: 'p_dst' undeclared (first use in this function)
    pixman-arm-neon.c: In function 'neon_composite_over_8888_0565':
    pixman-arm-neon.c:2074: error: 'x_dst' undeclared (first use in this function)
    pixman-arm-neon.c:2075: error: 'p_dst' undeclared (first use in this function)
    make[3]: *** [libpixman_arm_neon_la-pixman-arm-neon.lo] Error 1
    ...

    <--  snip  -->